### ISSUE TITLE
Should continuation indentation be 2 or 4 spaces? 

### ISSUE THREAD

**Issue by cgrushko** [facebook/ktfmt#14]
i.e., should code look like this: (2 spaces)

```
fun f() {
  val x =
    43
  aVeryLongFunctionName(
    a, b, c, d, e)
}
```

or like this? (4 spaces)

```
fun f() {
  val x =
      43
  aVeryLongFunctionName(
      a, b, c, d, e)
}
```

In favor of 2 spaces:
1. That's what IntelliJ's code conventions define. We don't know the reasons. It could be that it's just simpler this way.

In favor of 4 spaces:
1. It's looks more like Java.
2. Given `ktfmt`, it's as easy to format with 4 as it is with 2.

**Comment by cgrushko** [comment]
Personally, I'm in favor of 4, because of its similarity to Java (and because I'm more used to it).

**Comment by sgrimm** [comment]
I'm in favor of 4 as well not because of Java similarity but because I find

```kotlin
aFunctionWithAFinalFunctionArgument(
    a, b, c, d, e) {
  doOtherStuff()
}
```

more readable than

```kotlin
aFunctionWithAFinalFunctionArgument(
  a, b, c, d, e) {
  doOtherStuff()
}
```

**Comment by strulovich** [comment]
My Android Studio copy seems to use 4, as in:
```
    token(
        token,
        Doc.Token.RealOrImaginary.REAL,
        plusIndentCommentsBefore,
        /* breakAndIndentTrailingComment */ Optional.empty())
    val a = 324567 +
        234567890 + 2345678
```

I suggest keeping 4 for now in that case.

**Comment by strulovich** [comment]
Do we have any discussion going here? If not, we should close.
We do have double continuation in some cases now:

```
makeCall(
        arg1, arg2, arg3)
    .doMore()
```

**Comment by tyvsmith** [comment]
For reference, at Uber we use 2 indent, 4 continuation indent in Kotlin.

**Comment by ZacSweers** [comment]
The official kotlin style guide uses 2 for both, doesn't seem like continuation indent is treated differently (anymore)

**Comment by bethcutler** [comment]
The official Kotlin Intellij style guide has this reasoning for no continuation indents:
https://kotlinlang.org/docs/reference/code-style-migration-guide.html#differences-between-kotlin-coding-conventions-and-intellij-idea-default-code-style

At Google, we have been using this style, and encouraged ktlint to enforce it as well.  It is a more self-consistent style, where all blocks have no continuation indent, and the closing brace or paren is on a separate line.

**Comment by strulovich** [comment]
> several Kotlin constructions look a bit awkward when they are formatted this way

@bethcutler, do you have any idea what constructs they might mean? I think @cgrushko did a great job making all those calling chains with lambdas and what not work well for these cases.

**Comment by bethcutler** [comment]
I think the image included in the link I posted shows some decent examples; e.g. class members are all indented the same amount, regardless of if they are defined in the constructor or not.  Another example I like is that chained method calls are indented the same amount as statements in a block.

**Comment by hick209** [comment]
Closing this is both an old discussion and because now we have an option to set this up
https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt#L47
