### ISSUE TITLE
Canonical .editorconfig

### ISSUE THREAD

**Issue by sgrimm** [facebook/ktfmt#158]
This is kind of the opposite of #45 -- it'd be convenient to have a complete `.editorconfig` based on the plugin's current formatting rules, including editor-specific config properties for IntelliJ and any other editors people care to contribute.

Obviously this doesn't have to be generated by the plugin; it could be a hand-maintained file in the plugin source.

**Comment by cgrushko** [comment]
Do you mean emit an `.editorconfig` from the plugin? or store one in the plugin that matches the plugin's config?

**Comment by sgrimm** [comment]
Maintaining it as a standalone file people can download may be easier than making the plugin emit it on the fly, but either way would be useful.

Basically the idea is to make it easy to include editor settings in a project that uses ktfmt, such that the editor gets as close as possible to ktfmt's rules and ktfmt needs to make fewer changes. That's likely to be less error-prone than trying to tell people which editor settings to change manually.

**Comment by cgrushko** [comment]
I assume the target audience is users using an IDE other than IntelliJ, since there's a ktfmt plugin for IntelliJ?

**Comment by sgrimm** [comment]
The target audience I had in mind is actually IntelliJ users. To be clear, this is definitely a low-priority thing, but I'd want this for a few reasons:

* My experience is that there's often one person on a team who ends up not running ktfmt before committing code for whatever reason, so having the editor produce mostly-ktfmt-style code to begin with means that the subsequent cleanup commit won't churn the file's blame history as much.
* While I'm editing code, it's nice when the new code I'm typing looks similar to the existing ktfmt-formatted code. Otherwise I find myself hitting the Reformat hotkey pretty often to make everything line up.
* It will serve as a kind of machine-readable documentation of ktfmt's formatting rules.

**Comment by cgrushko** [comment]
Got it, thanks for clarifying!
It sounds like it's possible to hand-write the file, or maybe export it
from IntelliJ after tweaking its formatter?

**Comment by sgrimm** [comment]
Here's a hand-tweaked export of my IntelliJ settings; it isn't too far off, I think, but I am not confident I've gotten everything right (certainly not confident enough to want to submit it as a PR, but if you like, I can do that.)

[editorconfig.txt](https://github.com/facebookincubator/ktfmt/files/5766761/editorconfig.txt)

**Comment by cgrushko** [comment]
1. A PR sounds great, even if it's not perfect, especially if there's a way
to add this as a comment in the file.
2. Is this for the default style or dropbox style?
3. Should we name the file `.editorconfig-ktfmt.txt` or something like
that? I want to emphasize that it's not used for the ktfmt project itself,
but instead be downloaded and used in other projects. Maybe put it in a
subdirectory? editorconfigs? but then it's less discoverable. Anyway, I'm
open to ideas :)

**Comment by JavierSegoviaCordoba** [comment]
Before closing this issue, should be great to add `.editorconfig` for all styles (Google and Kotlinlang).

**Comment by hick209** [comment]
@sgrimm, could you work on what @JavierSegoviaCordoba proposed? I think that is a good idea.

@JavierSegoviaCordoba, if you feel adventurous and want to take a stab at this, I'd be happy to help ship it.

**Comment by sgrimm** [comment]
I should have time to have a crack at that this weekend.

**Comment by hick209** [comment]
@sgrimm feel free to submit a PR when you have something

**Comment by hick209** [comment]
Looks like we do, we just need to clean up the dropbox one, let me do that
