### ISSUE TITLE
Support JDK 8

### ISSUE THREAD

**Issue by cgrushko** [facebook/ktfmt#201]
Currently, ktfmt requires JDK 11 or newer because its dependency, google-Java-format 1.8, uses it in its Java fronted. 

This minimum requirement is problematic for ktfmt because:
1. The plug-in doesn't work on Android Studio 4.1.1 without manually running AS under a non-standard JRE. 
2. Any open-source project that uses ktfmt must also use JDK 11 or newer. 

Solution: for now, we'll fork GJF's JavaOutput (rename it to KotlinOutput) and downgrade our dependency to GJF 1.7, which supported JDK 8. 

In the future, if there are considerable changes to the GJF language agnostic parts that we want, we can do either of
1. Convince GJF maintainers to cut a version that only contains the engine (nothing there inherently needs a new JDK), or
2. Fork the GJF engine and bundle it into ktfmt.

**Comment by cgrushko** [comment]
1. ktfmt itself is easy to fix
2. ktfmt_idea_plugin is problematic: if I build against IJ 203, I get a version mismatch, because the 203 jars are built using JDK 11. I f I build against IJ 201, ktfmt fails because it no longer can handle Kotlin 1.3 on the classpath. Which leads to the next point -
3. The ktfmt plugin runs inside IJ with IJ's Kotlin stdlib on the classpath, which is not necessarily what ktfmt was built and intended to run with. That's very meh. The straightforward solution is to bundle ktfmt inside the plugin and load it using a separate class loader.

**Comment by JavierSegoviaCordoba** [comment]
4.2 RC is here, and Canary and Compose needs JDK 11 I think. Do you think it is better to support 1.8 instead of wait? Probable 4.2 stable is going to be presented in Google IO in May

**Comment by JavierSegoviaCordoba** [comment]
4.2 is released and it uses JDK 11 by default 🎉

**Comment by JavierSegoviaCordoba** [comment]
I am using ktfmt in arrow-kt repos and we need to use java 8, do you think you can fix this some day?

**Comment by hick209** [comment]
@JavierSegoviaCordoba, is this request for Java 8 support still current?

**Comment by JavierSegoviaCordoba** [comment]
No, you can close this
