### ISSUE TITLE
Formatting lists in KDoc

### ISSUE THREAD

**Issue by bethcutler** [facebook/ktfmt#208]
This is similar to https://github.com/facebookincubator/ktfmt/issues/66

If continuation indents are used in a list item, they are removed.
e.g. Before
```kotlin
/*
 * - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 *   labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 *   nisi ut aliquip ex ea commodo consequat.
 */
```

After
```kotlin
/*
 * - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 * labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 * nisi ut aliquip ex ea commodo consequat.
 */
```
(I think the "before" was preferable, though the "after" is acceptable)

If continuation indents are used in a way that slightly deviates from the above example, code blocks are added.
e.g. Before
```kotlin
/*
 * -   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 *     labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 *     nisi ut aliquip ex ea commodo consequat.
 *  - Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
 *    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
 *    mollit anim id est laborum.
 */
```

After
```kotlin
/*
 * - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 * ```
 *     labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 *     nisi ut aliquip ex ea commodo consequat.
 * ```
 * - Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
 * ```
 *    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
 *    mollit anim id est laborum.
 * ```
 */
```

This feels like a bad user experience.

Side note: when testing this issue, I had trouble producing consistent results.  Sometimes it seemed like the formatter silently gave up on a comment and didn't bother to format it at all.  Sometimes it added code blocks for apparently inexplicable reasons.

**Comment by cgrushko** [comment]
@strulovich , what do you think?
I have a vague memory of the KDoc formatter being smart, trying to guess the user's intention and e.g., adding triple-backticks. Maybe we should make it dumber so it's more predictable.

**Comment by strulovich** [comment]
I remember tried to make it work with how IJ is rendering KDoc, where things would be considered code blocks by accident, but not the same for the parser. I'll give it a whirl again to try and fix it.

**Comment by bethcutler** [comment]
Similar issue, nested lists are removed:
```kotlin
/**
 * Nested lists:
 *
 * * List 1
 *   * List 1a
 *   * List 1b
 * * List 2
 *   * List 2a
 *   * List 2b
 */
```

Is reformatted as
```kotlin
/**
 * Nested lists:
 *
 * * List 1
 * * List 1a
 * * List 1b
 * * List 2
 * * List 2a
 * * List 2b
 */
```

**Comment by strulovich** [comment]
When I take this example, place it Android Studio and look at the way it renders the KDoc is does not consider this to be a nested list.

![image](https://user-images.githubusercontent.com/4662781/125371276-610b0b00-e34e-11eb-9fd2-df4d252c5bc0.png)

Adding one more space would make it ok, and indeed Ktfmt goes crazy and makes it a piece of code. So there's something to fix it. However, it won't handle your case.

Would it be okay if we properly supported this case:
```
/**
 * Nested lists:
 *
 * * List 1
 *    * List 1a
 *    * List 1b
 * * List 2
 *    * List 2a
 *    * List 2b
 */
```

**Comment by bethcutler** [comment]
Yes, as long as there is one good case, I think we are ok.

It would be even nicer if ktfmt could convert the 2 and 4+ indent cases to be 3 so that the nested list would format properly, but that might be too much to ask!  Hard for our users to know that the correct formatting is exactly 3 spaces though...

**Comment by hick209** [comment]
As of v0.47 this is how it formats things
```
/*
 * -   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
 *     labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
 *     nisi ut aliquip ex ea commodo consequat.
 *  - Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
 *    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
 *    mollit anim id est laborum.
 *
 * Nested lists:
 *
 * * List 1
 *   * List 1a
 *   * List 1b
 * * List 2
 *   * List 2a
 *   * List 2b
 */
```

Closing issue
