### ISSUE TITLE
Style consideration: explicit constructor on a new line

### ISSUE THREAD

**Issue by bethcutler** [facebook/ktfmt#211]
If an explicit constructor has no or few arguments, it stays on the same line as the class, even if its annotated:
```kotlin
class Foo @Inject constructor() : Bar {
}
```

However, if the arguments won't fit on the same line, the constructor is moved to a new line without indentation:
```kotlin
class Foo
constructor(
  ... arguments...
) {
}
```

Then if there's an annotation, it gets a separate line:
```kotlin
class Foo
@Inject
constructor(
  ... arguments...
) {
}
```

Is it worth considering keeping the constructor on the same line as the class?  e.g.
```kotlin
class Foo @Inject constructor(
  ... arguments...
) {
}
```

**Comment by AllanWang** [comment]
This is a very common use case for Android custom views, as they contain 3 (or more) constructors. Pulling an example from Jetbrains

https://github.com/JetBrains/android/blob/c5057a6bd25016ef9b4acd890c04ccd5476500c4/android-kotlin/idea-android/testData/android/quickfix/viewConstructor/indirect.after.kt#L11-L13

```kt
class Foo @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : TextView<caret>(context, attrs, defStyleAttr)
```

**Comment by Kernald** [comment]
As a side-note, this is a very dangerous example as you're ignoring TextView's `defStyleAttr` default value (`com.android.internal.R.attr.textViewStyle`, not `0`), which results in your view being inherently broken.

**Comment by 111awesome111sauce111** [comment]
Good day there. Would it be possible to provide any news or plans? This issue becoming really noticeable when one works very closely with best practices like dagger injection. I feel like it was not always like that and before it was working as expected like showed at the bottom of this sub-section (https://kotlinlang.org/docs/classes.html#constructors). Thanks.

**Comment by hick209** [comment]
As this is a debated feature (no consensus we should pursue it within the ktfmt internal group) we have no intention of changing things regarding this. Closing the issue
