### ISSUE TITLE
Force trailing commas

### ISSUE THREAD

**Issue by sidvenu** [facebook/ktfmt#216]
Do we have the option to force the presence or absence of trailing commas? With its introduction in Kotlin, the codebase would potentially have a mix of both, and forcing the presence or absence of it would lead to consistency.

**Comment by blaugold** [comment]
:+1: for automatic insertion of trailing commas based on some rule. Forcing the absence of trailing commas is simple, but forcing them wherever possible wouldn't make sense. Maybe force one if the list is spanning 2 or more lines.

**Comment by att14** [comment]
It would be nice if `ktfmt` would have an opinion about either always trailing or never trailing, since right now, you can do either, and it leads to different behavior of the formatter. See #338.

**Comment by hick209** [comment]
https://github.com/facebook/ktfmt/commit/cec9b501428d5236c306ce2b50adc4cbe0338ffe
