### ISSUE TITLE
Formatting around triple-quote strings inconsistent

### ISSUE THREAD

**Issue by bethcutler** [facebook/ktfmt#237]
Here are two examples of triple-quote strings after formatting:

```kotlin
  val greeting = """
    hello
  """.toGreeting(myGreeting)

  val greeting =
    """
    hello
    welcome, very nice to meet you, ladies and gentlemen
  """.toGreeting(
      myGreeting
    )
```

In the second example, the extra characters in the string causes two effects:
- opening """ is moved to a new line
- "myGreeting" argument in the chained function is moved to a new line.

I believe this is because the number of characters exceeds that which would fit on a single line, despite the fact that it won't be displayed on a single line in either case.  This inconsistency is confusing to the user.

P.S. As a side note, the closing triple-quote indentation looks wrong in the second example, since it is not indented as much as the opening """.  I'm guessing this is because changing the indentation here would change the exact text in the triple-quote string, is that correct?

**Comment by toddobryan** [comment]
I suggested ktfmt and one of my colleagues saw this immediately. We actually got:
```
        val json =
            """
            [
              {
                "referenceID": "ac1",
                "name": "attributeConfig1",
                "description": "the first attribute config",
                "attributes": []
              }
            ]
        """
                .trimIndent()
```
which is just ugly beyond belief.

**Comment by JavierSegoviaCordoba** [comment]
They are not too deterministic, so if you fix them manually and you run again ktfmt, they will don't change, for example:

```kotlin
        val json =
            """
                [
                  {
                    "referenceID": "ac1",
                    "name": "attributeConfig1",
                    "description": "the first attribute config",
                    "attributes": []
                  }
                ]
            """
                .trimIndent()
```
