### ISSUE TITLE
Multiline TODO formatting is incorrect

### ISSUE THREAD

**Issue by ColtonIdle** [facebook/ktfmt#239]
IntelliJ/Android Studio won't highlight a multi-line TODO unless there is an extra space if the TODO spans multiple line.

See the attached video. When I add an extra space I see that the TODO is multi-line, if I remove the extra space it is just treated as another regular comment.

To be clear, in the video I only press the auto-reformat shortcut once. The adding and removal of the extra space is me typing/deleting manually in order to show the highlighting done by the IDE.

https://user-images.githubusercontent.com/31751141/120054284-0b2c0f00-bffd-11eb-9e38-6fe105aff777.mp4

**Comment by hick209** [comment]
Looks like this is issue comes from Google Java Format
![image](https://github.com/facebook/ktfmt/assets/927983/d28e505b-8cb5-456e-849c-0bc91a7daab7)

I'd recommend filing this issue there
