### ISSUE TITLE
Crash on legal (but non-standard) getter code

### ISSUE THREAD

**Issue by bethcutler** [facebook/ktfmt#241]
```kotlin
  val testGetter: Boolean; get() {
    return "OK" == "foo"
  }
```

The formatter crashes on this code with the error:
```error: expected token: ';'; generated get instead```

Removing the ; and putting the get() on the following line fixes the exception.

**Comment by cgrushko** [comment]
I'm thinking we should remove the semicolon from the formatted code, so this becomes
```
val testGetter: Boolean
   get() {
     return "OK" == "foo"
   }
```
(or whatever ktfmt outputs for a getter without a semicolon preceding it).

@bethcutler  @strulovich  thoughts?

**Comment by mpetrov** [comment]
Stumbled into this example in the wild, in case it's useful as a repro:
https://github.com/JetBrains/kotlin/blob/723ef8f1fba8664f3948f545f5d7091047d0920c/compiler/frontend/src/org/jetbrains/kotlin/types/expressions/PatternMatchingTypingVisitor.kt#L103

**Comment by cgruber** [comment]
Honestly, for things this small, I feel like that one could get one-liner'ed.

```
val testGetter: Boolean get() { return "OK" == "foo" }
```

This connects back to the "lambda formatting" issues I see elsewhere here. But generally I do small things like this in one line.

**Comment by strulovich** [comment]
@cgruber, I agree that in the case of a really simple getter this may look better.
If you'd like to send a PR we can make sure it looks reasonable on our existing code and take it. (I assume we will only allow this 1-line if only a `get` or `set` exists, and not both)

**Comment by hick209** [comment]
On v0.47 this no longer crashes and formats to
```
  val testGetter: Boolean; get() {
    return "OK" == "foo"
  }
```
