### ISSUE TITLE
ktfmt misplaces opening quotes of raw string literals

### ISSUE THREAD

**Issue by fcurts** [facebook/ktfmt#251]
ktfmt 0.28, code style "Default"

Before:

```
object Messages {
  val msg1 = """
    foo asfasf asdf asf asdfasf asdf.
    bar asdf sf asdf asdfasdf as.
    baz asdf dsaf asdf sfd .
  """.trimIndent()
}
```

After:

```
object Messages {
  val msg1 =
      """
    foo asfasf asdf asf asdfasf asdf.
    bar asdf sf asdf asdfasdf as.
    baz asdf dsaf asdf sfd .
  """.trimIndent()
}
```

**Comment by cgrushko** [comment]
The engine wasn't designed at the time for multi line strings, and considers the string literal to not fit in the first line. 

Given that multi line strings are coming to Java, we can hope that google-java-format (whose engine ktfmt is using) will gain support for these.

**Comment by fcurts** [comment]
Thanks for the explanation. 

> Given that multi line strings are coming to Java

Just to be clear, Java text blocks went GA in Java 15 (September 2020).

**Comment by att14** [comment]
The ability to reformat `.trimIndent()` blocks so all the indents are matching would be super userful.

**Comment by kevinb9n** [comment]
Here's how we expect to address it in GJF (whenever we do): https://github.com/google/google-java-format/issues/883

If it helps, that includes a pithy description of how the language feature works so you could account for exactly how Kotlin's design differs.

**Comment by cgrushko** [comment]
@kevinb9n, unfortunately they didn't have you in the Kotlin design committee 🤣 

In Kotlin, according to IntelliJ at least, these two statements are equivalent:
```
val a = """
     asd
     asd
          """
val a = "\n     asd\n     asd\n          "
```

and so are these:
```
val a = """
     asd
     asd
 """

val a = "\n     asd\n     asd\n "
```

In other words, we can't change any indentation without changing the value of the literal.
(Kotlin also doesn't have \s, and any trailing spaces in multiline strings are preserved by the compiler)

**Comment by att14** [comment]
Would it be possible to only correct the indentation if `trimIndent` is invoked?

```
val a =
     """
     foo
     """.trimIndent()
 val b = "foo"
 a == b
res1: kotlin.Boolean = true
```

**Comment by cgrushko** [comment]
I'm in favor of giving trimIndent special treatment, but we can't commit to a timeline. If we're lucky we can copy the support from GJF.

**Comment by hick209** [comment]
What we do in v0.47
```
object Messages {
    val msg1 =
        """
    foo asfasf asdf asf asdfasf asdf.
    bar asdf sf asdf asdfasdf as.
    baz asdf dsaf asdf sfd .
  """
            .trimIndent()
}
```

This here is what Google Java Format does
```
➜ cat Test.java
class Test {
  public static final String msg1 = """
      foo asfasf asdf asf asdfasf asdf.
      bar asdf sf asdf asdfasdf as.
      baz asdf dsaf asdf sfd .
  """.trimIndent();

  void foo() {
    loader(
        """
        Foobar
        %s
        """.formatted(decl.joinToString(""))
    );
  }
}

➜  java -jar google-java-format-1.22.0-all-deps.jar Test.java
class Test {
  public static final String msg1 =
      """
          foo asfasf asdf asf asdfasf asdf.
          bar asdf sf asdf asdfasdf as.
          baz asdf dsaf asdf sfd .
      """
          .trimIndent();

  void foo() {
    loader(
        """
        Foobar
        %s
        """
            .formatted(decl.joinToString("")));
  }
}
```

We inherit from GJF so if you want some base change, I'd request you open an issue there (https://github.com/google/google-java-format), if there isn't one open already.
