### ISSUE TITLE
`format` re-parses after adding newlines, which can cause crashes

### ISSUE THREAD

**Issue by nreid260** [facebook/ktfmt#277]
The current implementation of the formatter goes like `parse > google_java_format > print > parse > remove_redundant_elements > print`. This sequence can put the code in the middle `parse` step into a bad state.

Example:
```
val foo: Int; get() = 0; set() { }
```
becomes
```
val foo: Int;
  get() = 0;
  set() { }
```
which cannot be reparsed.

**Comment by nreid260** [comment]
Amazingly, it does seem to work if the breaks come before the semicolons!

```
val foo: Int
  ;get() = 0
  ;set() { }
```
 parses and behaves just fine.

**Comment by hick209** [comment]
On v0.47, this here
```
var foo: Int; get() = 0; set(value) { }
```
Turns into
```
var foo: Int
  get() = 0
  set(value) {}
```

Which is valid and can be reformatted without issues.

**Comment by nreid260** [comment]
I think this was fixed when I removed some of the parse/print phases.
