### ISSUE TITLE
Homebrew recipe

### ISSUE THREAD

**Issue by cgruber** [facebook/ktfmt#312]
Using ktfmt as a part of tooling can be very useful, but having in brew (and/or aptitude, etc.) for package installations on developer machines is pretty handy. 

Any chance someone is looking into that?

**Comment by cgrushko** [comment]
@cgruber , long time no see :)

I'm not aware of anyone at Meta looking into that.

**Comment by cgruber** [comment]
Carmi! 

Anyway, trying to figure out if we are going to use it, and to what extent, and I'd like to not have to use it from within gradle for pre-commit or pre-push hooks, and having a good install package for dev or CI environments would be sweet.

**Comment by hick209** [comment]
Thanks for pointing that out @chenrui333 😃
