### ISSUE TITLE
context receivers support

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebook/ktfmt#314]
Currently, `context` add an unnecessary breakline:

```kotlin
context(ScanResult)

internal val ClassInfo.contextClasses: List<KClass<out Any>>
  get() =
    getClassesWithAnnotation(this.name).map { contextClassInfo ->
      contextClassInfo.loadClass().kotlin
    }
```

should be:

```kotlin
context(ScanResult)
internal val ClassInfo.contextClasses: List<KClass<out Any>>
  get() =
    getClassesWithAnnotation(this.name).map { contextClassInfo ->
      contextClassInfo.loadClass().kotlin
    }
```

**Comment by strulovich** [comment]
It is likely we will only fix this when this comes out of preview. Happy to accept a PR once the dependencies sort themselves out (though it looks it might be future compatible from the fact Ktfmt doesn't crash on this)

**Comment by JavierSegoviaCordoba** [comment]
I would like to know how it will be combined with annotations.

### 1
```kotlin
context(Persistence)
@Provider class Repo
```
### 2

```kotlin
context(Persistence)
@Provider
class Repo
```
### 3

```kotlin
@Provider
context(Persistence)
class Repo
```

The first one is which I like more but if there are a lot of annotations it will not look very good, so I think 3 is the best one.

**Comment by JavierSegoviaCordoba** [comment]
@strulovich I tried this myself but after updating Kotlin to 1.7.10, I cannot get the context receivers in `visitNamedFunction`, I got an empty list even though the `KotlinInput` shows clearly they are there.

Not sure if I am missing something.

**Comment by JavierSegoviaCordoba** [comment]
@strulovich as they are not going to be on 1.8.0, can this be prioritized a bit, please?
