### ISSUE TITLE
There are no `*-with-dependencies` jar artifacts getting uploaded to github releases

### ISSUE THREAD

**Issue by ZacSweers** [facebook/ktfmt#321]
The README says to download the formatter to run a fat jar CLI, but there is no such artifact getting uploaded with releases despite the README linking to them. Am I missing something?

<img width="838" alt="image" src="https://user-images.githubusercontent.com/1361086/170899667-742dcd29-b2b2-4649-814b-853492f1c01d.png">

Where "Download the formatter" just links to here: https://github.com/facebookincubator/ktfmt/releases. Releases do not contain this fat jar artifact though

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/1361086/170899718-bd34d35f-8529-4e40-8cd6-d5b48bac67ef.png">

**Comment by ZacSweers** [comment]
It looks like the last release to include them was `0.21` – https://github.com/facebookincubator/ktfmt/releases/tag/v0.21. I do see them uploaded to sonatype though: https://repo1.maven.org/maven2/com/facebook/ktfmt/0.37/

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1361086/170899862-129dc9d3-2727-4466-91a4-26d00b53df56.png">


Is something broken with github releases or is it expected to just fetch them from central instead?

**Comment by cgrushko** [comment]
Whoops, that's not a good experience. Let me see how hard it is to automatically upload stuff to GitHub's Releases (I think 0.21 is around the time I automated releases)

**Comment by hick209** [comment]
We have them on the latest releases (v0.47+)
