### ISSUE TITLE
Version 0.41 behaves differently between CLI and plugin

### ISSUE THREAD

**Issue by nreid260** [facebook/ktfmt#361]
CLI produces:
```
fun example() {
  """
    |
  """
    .trimMargin()
}
```

IntelliJ's `Reformat Code` produces:
```
fun example() {
  """
    |
  """.trimMargin()
}
```

**Comment by hick209** [comment]
I believe this was fixed when we released the new version of the plugin.

Feel free to reopen if issue persists
