### ISSUE TITLE
Optimize imports does not work for wildcard imports

### ISSUE THREAD

**Issue by StefanLobbenmeier** [facebook/ktfmt#366]
In https://github.com/facebook/ktfmt/issues/17 I saw that imports are supposed to be optimised now. But there might have been a regression with wildcard imports, or maybe it was never supported.

To reproduce:
1. Checkout https://github.com/StefanLobbenmeier/kftmt-example `git clone https://github.com/StefanLobbenmeier/kftmt-example.git`
2. run `gradlew spotlessApply`
3. The import in Main.kt stays: https://github.com/StefanLobbenmeier/kftmt-example/blob/ab6f3209604855f8e3400fdc0d494461d4ea266e/src/main/kotlin/Main.kt#L1

Also spotlessCheck seems to not care about the redundant import:
![image](https://user-images.githubusercontent.com/36509607/201151796-6dede450-9997-4f11-a85d-2a58a42ff069.jpeg)

**Comment by StefanLobbenmeier** [comment]
I see, fair enough. Making IntelliJ avoid wildcards should be a good workaound. Thanks for the fast reponse!

**Comment by StefanLobbenmeier** [comment]
Just for anyone else that might have the same issue, this is the .editorconfig to change those import settings:

```
[{*.kt,*.kts}]
ij_kotlin_imports_layout = *, ^
ij_kotlin_name_count_to_use_star_import = 2147483647
ij_kotlin_name_count_to_use_star_import_for_members = 2147483647
ij_kotlin_packages_to_use_import_on_demand =
```

**Comment by PhilGlass** [comment]
If you have import aliases the above is slightly wrong and won't match ktfmt output - it should be `ij_kotlin_imports_layout = *`, not `ij_kotlin_imports_layout = *, ^` ([see these examples](https://pinterest.github.io/ktlint/0.49.0/rules/configuration-ktlint/#import-layouts)).

```
[{*.kt,*.kts}]
ij_kotlin_imports_layout = *
ij_kotlin_name_count_to_use_star_import = 2147483647
ij_kotlin_name_count_to_use_star_import_for_members = 2147483647
ij_kotlin_packages_to_use_import_on_demand =
```
