### ISSUE TITLE
Can we always assume UTF8?

### ISSUE THREAD

**Issue by nreid260** [facebook/ktfmt#373]
Right now, ktfmt uses the default system charset to parse files. This has caused some headaches when users have unusual charsets as the default. Usually it ends up mangling non-ASCII characters.

Kotlin specifies that all source files must be in UTF8, so it's reasonable that ktfmt could make the same assumption. We could ignore the system default and always use UTF8.

The only caveat I can see with this change is that, ktfmt may crash when invoked on the command line with literal text, on a system using a different default encoding. This usecase seems pretty unlikely, so maybe not worth worrying about compared to the advantages. Also, in this situation, do we emit the formatted code using the system encoding?

**Comment by cgrushko** [comment]
> Kotlin specifies that all source files must be in UTF8

I couldn't find a reference to this (outside of Google's style guide), but this sounds reasonable. Maybe worth running this by folks in the Kotlin slack.

**Comment by nreid260** [comment]
Oh weird. I thought UTF8 was a language level thing, but maybe I mixed that up with https://developer.android.com/kotlin/style-guide
