### ISSUE TITLE
Feature request: ability to specify file of files to format

### ISSUE THREAD

**Issue by ZacSweers** [facebook/ktfmt#377]
If you try to run ktfmt's CLI over the `find` output of a large codebase, you can eventually exceed the maximum number of arguments. It would be great if these could be stored in a file and fed to the CLI via alternative parameter.

```
tooling/scripts/format.sh: line 23: ./config/bin/ktfmt: Argument list too long
```

**Comment by cgrushko** [comment]
As a workaround, does something like the following work?

```
find $DIR -name \*.kt | xargs tooling/scripts/format.sh
```

**Comment by ZacSweers** [comment]
Sorry for the delay! That does indeed work 👍

**Comment by grodin** [comment]
It's not documented apparently, but if the only argument you pass is `@file` ktfmt takes what would normally be its command line arguments from `file`, one argument per line. So what would be 

```
> ktfmt --google-style --dry-run some/dir/file1.kt some/other/dir/file2.kt build.gradle.kts ...
```

will do the same as

```
> cat args
--google-style
--dry-run
some/dir/file1.kt
some/other/dir/file2.kt
build.gradle.kts
...

> ktfmt @args
```

Introduced in [this commit][commit].

[commit]: https://github.com/facebook/ktfmt/commit/0901f21f64bda7004788b5623ec23aef724972b1

**Comment by nreid260** [comment]
It looks like this has been fixed. Can someone close the issue?
