### ISSUE TITLE
Different behavior with IntelliJ plugin and Maven plugin with same config

### ISSUE THREAD

**Issue by vahidmah** [facebook/ktfmt#383]
I have ktfmt Intellij plugin version 1.1.0.42 installed with style set to default. The plugin is enabled. 

In my project which is mix of Java & Kotlin I have configured [Spotless with ktfmt ](https://github.com/diffplug/spotless/tree/main/plugin-maven#kotlin) config for maven. The plugin is configured like:

```xml
<plugin>
  <groupId>com.diffplug.spotless</groupId>
  <artifactId>spotless-maven-plugin</artifactId>
  <version>2.30.0</version>
  <configuration>
    <kotlin>
      <ktfmt>
        <version>0.42</version>
        <style>DEFAULT</style>
     </ktfmt> 
    </kotlin>
 </configuration>
</plugin>
```

The problem is when I format my code with IDE shortcut (Reformat Code ctrl+alt+L), it change the format to 4 spaces but if I run `spotless:apply` goal the format will change to 2 spaces.

**format with Intellij plugin**
```kotlin
class MyClass {
....fun run() {}
}
```

**format with maven goal**
```kotlin
class MyClass {
..fun run() {}
}
```
Shouldn't both behave the same, since the config is the same?

**Comment by davidtorosyan** [comment]
Interesting. For reference, the default (and google style) is a 2 space indent. The get 4 spaces, you'd need to format with either [kotlinlang or dropbox style](https://github.com/facebook/ktfmt/blob/b25b5a00e07f8354fb8da047de5715bf42c9e40d/core/src/main/java/com/facebook/ktfmt/format/Formatter.kt#L51).

The spotless plugin must be using default then (like your code snippet indiciates), and your IDE is probably using something else.

I know you mentioned that your plugin is set to default, but can you double check your IDE configuration using the instructions in the [README](https://github.com/facebook/ktfmt#intellij-android-studio-and-other-jetbrains-ides)? Maybe share the [.editorconfig](https://www.jetbrains.com/help/idea/configuring-code-style.html#editorconfig) file for us to take a look.

**Comment by gino-m** [comment]
Our team has been having the same issue. We're using the `com.ncorti.ktfmt.gradle 0.11.0` Gradle plugin to check and fix formatting with `googleStyle()`, and the ktfmt 1.1.0.42 plugin set to `Google (Internal)`. Some examples:

Organize imports in Android Studio:

```
import java8.util.function.Consumer
import timber.log.Timber
import javax.inject.Inject
```

ktfmtFormat via Gradle plugin:

```
import java8.util.function.Consumer
import javax.inject.Inject
import timber.log.Timber
```

Via AS plugin:

```

  @Inject
  EphemeralPopups popups;

  private LocationOfInterestSelectorViewModel viewModel;
  private LocationOfInterestSelectorDialogBinding binding;

  @Nullable
  private ArrayAdapter listAdapter;
``

Via Gradle plugin:
```
  @Inject EphemeralPopups popups;

  private LocationOfInterestSelectorViewModel viewModel;
  private LocationOfInterestSelectorDialogBinding binding;

  @Nullable private ArrayAdapter listAdapter;
```

**Comment by vahidmah** [comment]
@davidtorosyan,

I exported code style to an `editorconfig` file following these [steps](https://www.jetbrains.com/help/idea/editorconfig.html#98580cd6). 
[editorconfig.zip](https://github.com/facebook/ktfmt/files/10608890/editorconfig.zip)

**Comment by davidtorosyan** [comment]
@vahidmah thanks for sharing, I think that explains it.

If you're intending to use `DEFAULT` formatting, you need to your `.editorconfig` to match [.editorconfig-default](https://github.com/facebook/ktfmt/blob/main/docs/editorconfig/.editorconfig-default).

Your `.editorconfig` looks like this:
```
[*]
...
indent_size = 4

[{*.kt,*.kts}]
# no indent size specified
```

While the correct config has:
```
[{*.kt,*.kts}]
...
indent_size = 2
```

So all you need to do is copy the contents of the file I linked to the `[{*.kt,*.kts}]` section of your `.editorconfig`.

Closing this issue, please reopen if that doesn't fix it.

---

@gino-m that sounds like a different problem (I'm guessing you're running two different versions of ktfmt). Can you open a separate issue?

**Comment by vahidmah** [comment]
I think the issue still persists and not resolved. I deleted my `.editorconfig` file from the project. When I format my code using IJ's plugin and spotless Maven the result is different as I mentioned above
