### ISSUE TITLE
Q: any option to align `->` in `when`?

### ISSUE THREAD

**Issue by dxxvi** [facebook/ktfmt#384]
This is a `when` example:
```
when (x) {
  "some very long value" -> TODO()
  else -> TODO()
}
```
I would like to align those 2 `->` like in scalafmt
```
when (x) {
  "some very long value" -> TODO()
  else                   -> TODO()
}
```
Is it possible?

**Comment by hick209** [comment]
I'm closing the issue as this is not something that we intend to work on, but we would welcome a PR so feel free to submit one
