### ISSUE TITLE
 Unicode characters through stdin not handled properly with non-standard UTF setting

### ISSUE THREAD

**Issue by UteHaus** [facebook/ktfmt#390]
When I format with ktfmt and have (german) umlauts like "ä" oder "ü" in a string value, I get this warning:
![grafik](https://user-images.githubusercontent.com/31124997/222682397-26269cc9-cc4c-446e-bdd2-c3c04d6510ad.png)

The input value is: "Müller Maha Ag"
Actual Result with ktfmt: "M�ller M�ha Ag"
Expected Result:  "Müller Maha Ag"

My setup:
IDE: IntelliJ IDEA 2022.3.2 
JAVA: 17 
Kotlin:  1.7.22
OS: Windows 11

**Comment by UteHaus** [comment]
It is a Intellij problem.

**Comment by nreid260** [comment]
@hick209 This is probably fixed. UTF8 is now assumed for all inputs and the system charset is ignored.

**Comment by hick209** [comment]
Confirmed that this is now fixed (tested on 0.49)
