### ISSUE TITLE
IDEA plugin is not published since 0.43

### ISSUE THREAD

**Issue by sergei-lapin** [facebook/ktfmt#399]
There's nothing much to add to the title: there are no nor 0.43 nor 0.44 version of IDEA plugin present on JetBrains marketplace

**Comment by cgrushko** [comment]
Our plugin (which is a copy-paste of google-java-format's) has had compatibility issues for some time now (i.e., APIs that JetBrains deprecated) but we never got around to updating the plugin. Looks like JetBrains now rejects updates that still have these compatibility issues (which is reasonable).

The path forward is to copy-paste google-java-format's plugin again and apply our changes on top of the fork.

**Comment by jiqimaogou** [comment]
I think we can have a jar publish in github, so we can install it offline

**Comment by simonhauck** [comment]
Hi,

I wanted to ask if there are any updates regarding this issue. 

We just stumbled across this issue today in our project, since the [gradle ktfmt plugin](https://github.com/cortinico/ktfmt-gradle) has now updated to the latest version of ktfmt and the formatting changed. Now the IntelliJ plugin and the format tasks generate different outputs and it would be amazing to have the auto save functionality back :)

Is there any way we can support?

**Comment by greyhairredbear** [comment]
I'd be happy to give the copy-paste approach proposed by @cgrushko a try and open a PR if I don't run into any unexpected issues.

**Comment by JavierSegoviaCordoba** [comment]
@greyhairredbear any update? If you got some blocker maybe getting it published on Github as a zip would be a workaround for a while.

**Comment by greyhairredbear** [comment]
Haven't really gotten to it unfortunately. Mainly took a look around the google-java-format plugin code. I have the impression it should not be too much of a hassle, maybe I'll have some time to spare on one evening this week - but no guarantees there.

**Comment by greyhairredbear** [comment]
Just as a small heads up: Started working on this, but I can't make any promises how much time I can spend. Any changes I push should be visible in #420

**Comment by okarmazin** [comment]
FYI `1.1.0.46` is published again

<img width="1057" alt="image" src="https://github.com/facebook/ktfmt/assets/18285187/9005d282-5a8e-4293-9578-423315ebacdb">

**Comment by greyhairredbear** [comment]
Correct, already have it in use. I suppose it still would make sense to merge #420 (or if the updated plugin is based on some other unmerged code that code) at some point - just to be on par with the google-java-format plugin and not use deprecated APIs anymore.
