### ISSUE TITLE
Incorrect detection of unused import in Gradle Kotlin DSLs using new assignment operator

### ISSUE THREAD

**Issue by cloudshiftchris** [facebook/ktfmt#411]
Gradle 8.2 stabilized a new assignment operator (`import org.gradle.kotlin.dsl.assign`) that allows for setting Gradle `Property` values using `=` (delegates to `.set()`).

This was an [issue](https://youtrack.jetbrains.com/issue/KTIJ-24390/) for IntelliJ until recently-released 2023.2.

ktfmt erroneously identifies the import as unused and removes it, resulting in compilation errors

**Comment by hick209** [comment]
This seems like a bit of an [edge case](https://blog.gradle.org/simpler-kotlin-dsl-property-assignment#:~:text=option%20to%20overload%20the%20%3D%20assignment%20operator%20for%20final%20properties&text=written%20as%20a%20Kotlin%20compiler%20plugin), but I don't see why we could not add this exception to the [list here]([https://github.com/facebook/ktfmt/blob/58777b2e386128f15042de5c2698511ef0771352/co[…]/main/java/com/facebook/ktfmt/format/RedundantImportDetector.kt](https://github.com/facebook/ktfmt/blob/58777b2e386128f15042de5c2698511ef0771352/core/src/main/java/com/facebook/ktfmt/format/RedundantImportDetector.kt#L34-L79)).

Feel free to submit a PR if you want this done faster
