### ISSUE TITLE
Update the pics in [demo](https://github.com/facebook/ktfmt#demo)

### ISSUE THREAD

**Issue by atulgpt** [facebook/ktfmt#413]
I tried with the latest [ktlint](https://github.com/pinterest/ktlint/releases/tag/0.50.0) and tried to run the sample code shown in the [demo](https://github.com/facebook/ktfmt#demo). And some of the result is updated we should update the screenshot over there

My findings are as below

Original code
<img width="1278" alt="orig" src="https://github.com/facebook/ktfmt/assets/11026203/6269e573-e09a-4f17-90d0-f9584fdca478">

Formatted code
<img width="1195" alt="formatted" src="https://github.com/facebook/ktfmt/assets/11026203/13a80825-1af2-4945-92e5-ecc40161d46c">

**Comment by hick209** [comment]
If you want, you could update those yourself @atulgpt, we'd be happy to merge your Pull Request

**Comment by atulgpt** [comment]
HI, @hick209 is current code, font, and color theme ok or is there any particular preference for it?

**Comment by hick209** [comment]
@atulgpt they LGTM. If you could remove any visual artifacts such as the red symbols and red squiggly line, that would be great 😃

**Comment by hick209** [comment]
cc @cgrushko in case you have strong thoughts about this
