### ISSUE TITLE
Publishing workflow is broken

### ISSUE THREAD

**Issue by greyhairredbear** [facebook/ktfmt#419]
The following workflow run was unsuccessfull:  https://github.com/facebook/ktfmt/actions/runs/6224781309

Thus, version `0.45` has not been published to Maven Central. I suppose this has already been noticed - reporting just for the improbable case this has slipped...

**Comment by liutikas** [comment]
It is in maven central as far as I can tell https://repo1.maven.org/maven2/com/facebook/ktfmt/0.45/

**Comment by greyhairredbear** [comment]
Hm, that's quite interesting - might have just stumbled into an edge case, where the build was not online yet and gradle already tried to fetch `0.45` (was trying to build the idea-plugin). Seems to work now, so I'm closing this. Thank you for the update
