### ISSUE TITLE
Blank lines between global constants

### ISSUE THREAD

**Issue by russellw** [facebook/ktfmt#42]
Generally speaking, ktfmt seems to have a policy of putting a blank line between top-level declarations. Which for most things, such as functions and classes, is good!

It's not as good for global constant declarations, e.g. in a parser I'm writing at the moment, the token constants end up looking like this:

private const val EOF = (-1).toChar()

private const val AND = 0.toChar()

private const val ARROW = 1.toChar()

private const val EQUALS = 2.toChar()

private const val GREATER_EQUALS = 3.toChar()

private const val IDENTIFIER = 4.toChar()

private const val INT_LITERAL = 5.toChar()

private const val LESS_EQUALS = 6.toChar()

private const val NOT_EQUALS = 7.toChar()

... etc

which doesn't look so good.

Any chance of removing the blank lines between global constants?

**Comment by cgrushko** [comment]
I think it makes sense - it'll make top-level properties behave like class member properties (i.e., preserve a single black line if it's there, otherwise don't force a newline).
