### ISSUE TITLE
ktfmt 0.45 is shipping against ancient milestone version of Kotlin

### ISSUE THREAD

**Issue by liutikas** [facebook/ktfmt#421]
[`0.44`](https://repo1.maven.org/maven2/com/facebook/ktfmt/0.44/ktfmt-0.44.pom) depends on `1.6.10`, however [`0.45`] (https://repo1.maven.org/maven2/com/facebook/ktfmt/0.45/ktfmt-0.45.pom) depends on `1.6.20-M1`. It seems really surprising that it is using a milestone of such an old release.

It seems to have happened in https://github.com/facebook/ktfmt/pull/400

Can it just point to 1.6.20? or 1.7.0?

**Comment by liutikas** [comment]
for context, we track all of our prebuilts and using such an old milestone version raises some eyebrows

**Comment by hick209** [comment]
This is solved on the [v0.46](https://github.com/facebook/ktfmt/releases/tag/v0.46), which targets Kotlin 1.8.22
