### ISSUE TITLE
Cannot handle formatting `context` keyword

### ISSUE THREAD

**Issue by Elforama** [facebook/ktfmt#429]
When using `context` for context receivers, the formatter throws the following error: 
```
error: expected token: 'context'; generated ( instead
```

The code it highlights for the error is:
```
val viewEffectMap: MutableMap<KClass<out ViewEffect>, context(Context, View) (effect: ViewEffect) -> Unit> = mutableMapOf()
```

This breaks usage of using this context receiver feature with formatting.

**Comment by JavierSegoviaCordoba** [comment]
I am seeing this with

```kotlin
public interface A<T> {
    
    // ...
     
    @SomeAnnotation
    public infix fun someFun(block: context(SomeScope<T>) T.() -> Unit): T = invoke(block)
}
```

**Comment by JavierSegoviaCordoba** [comment]
@bddckr, do you plan to maintain the context receivers/params integration next year?

**Comment by bddckr** [comment]
@JavierSegoviaCordoba Sorry for the late reply.

My team continues using ktfmt and context receivers, so I will keep the minimum working. I know there will likely be a few changes to stay current with the Kotlin changes.

However, I'm stretched a bit thin for at least the next half a year. Therefore, I may not get around to anything but the bare minimum. Someone else may be interested in getting more done - more test scenarios and more features should be covered in ktfmt eventually for context receivers/parameters.

**Comment by hick209** [comment]
Fixed by https://github.com/facebook/ktfmt/commit/dafd1cbb34a049fd8606213f16ea63569f8e3d05
