### ISSUE TITLE
0.47 trailing comma changes cause class definitions to be formatted weirdly

### ISSUE THREAD

**Issue by msfjarvis** [facebook/ktfmt#436]
<sub>I am so sorry about the title I genuinely could not make words happen</sub>

After the ktfmt 0.47 upgrade a lot of my class definitions got reformatted to put the entire constructor into one line and the class being extended into the next, which IMO is a regression from the older behavior. Here's an example of such a diff:

```diff
-public sealed class CryptoException(
-  message: String? = null,
-  cause: Throwable? = null,
-) : Exception(message, cause)
+public sealed class CryptoException(message: String? = null, cause: Throwable? = null) :
+  Exception(message, cause)
```

The existing version (which ktfmt <= 0.46 was okay with) has less horizontal spread which aids readability for me.

**Comment by cgrushko** [comment]
@nreid260 , what do you think?

**Comment by nreid260** [comment]
This is WAI. The trailing comma was being used as a "hint" to force a certain linebreak pattern. Automated trailing commas was implemented to remove that hinting capability.

That said, we can't delete comments, and those are always line terminators, so you could force the original layout with empty comments. Or stop using --google-style.
