### ISSUE TITLE
Adding target jar to releases

### ISSUE THREAD

**Issue by AlexandrosAlexiou** [facebook/ktfmt#450]
Hello,
Any plans in adding `jar` builds to the releases? This would allow for ease of integration with other developer tools. (eg. [Mason](https://github.com/mason-org/mason-registry))

Thanks

**Comment by hick209** [comment]
I don't see a reason not to do that.
I'll work on getting them for the next release

**Comment by AlexandrosAlexiou** [comment]
> I don't see a reason not to do that. I'll work on getting them for the next release

Thanks!
