### ISSUE TITLE
ktfmt doesn't seem to work in IJ 2024.1.1

### ISSUE THREAD

**Issue by rock3r** [facebook/ktfmt#463]
I have the ktfmt plugin installed and enabled in IJC 2024.1.1:

![image](https://github.com/facebook/ktfmt/assets/153802/f1ad0e0c-b43c-41fb-9d77-523715615d5c)

When I reformat the file (cmd-shift-l), it looks like it's using IJ's formatter. If I run ktfmt from the command line, the formatting of the file that I just theoretically reformatted in the IDE changes. This shows ktfmt was not used.

**Comment by ColtonIdle** [comment]
What if you restart the IDE? Wonder if its this issue that was closed: https://github.com/facebook/ktfmt/issues/229

**Comment by rock3r** [comment]
Hi Colton! No, still doesn't seem to work after restarting the IDE.

**Comment by greyhairredbear** [comment]
Hmmm, that's interesting. I've `2024.1.1 (241.15989.150 build)` with ktfmt plugin version `1.1.0.49` and it's working with that configuration for all the available styles... Do you have any other formatting tools running? Or maybe an `.editorconfig` file, which is being used by IntelliJ?

**Comment by rock3r** [comment]
Sorry it took me a while to get back to you, I was mostly travelling for work :) No .editorconfig file, and no other formatting plugins.

<img width="748" alt="image" src="https://github.com/facebook/ktfmt/assets/153802/29f73b16-0a35-4ee3-a287-353e2865e2dc">

Is it possible that the issue is that I have the reformatting scope set to "Only changes uncommitted to VCS"? If I set it to "whole file" it seems to work fine.

**Comment by greyhairredbear** [comment]
Oh, that's actually quite possible. I think I know where the issue might be, hopefully I can find the time to look into that soon. Thank you for the hint!

**Comment by hovterteryan** [comment]
Any update on this? Issue exists on Android Studio Koala based on IJ 2024.1.1

**Comment by rock3r** [comment]
The next version will work fine in all IJ versions up to 242. I fixed it in #501

**Comment by greyhairredbear** [comment]
Hi @rock3r, nice work on converting the IntelliJ Plugin to Kotlin! 👏 

It has been quite a while since I've been able to look into ktfmt, but I have a question on this: Did the update fix the issue with the "Only changes uncommited to VCS"-setting? My guess was that it had something to do with `getFeatures()` from the `KtfmtFormattingService` not returning any partial formatting features. And since I saw the return value of the method did not really change after the update, I got curious :)

**Comment by rock3r** [comment]
@greyhairredbear no, I didn't alter the plugin behaviour. That is still essentially doing nothing. I also think it's due to the features being declared, but don't know how to implement partial reformatting. Maybe @hick209 can help?

**Comment by greyhairredbear** [comment]
> but don't know how to implement partial reformatting

Yes, me neither. I can't recall if I tried just setting the features, using the existing `KtfmtFormattingTask` and just see what it does... Seems to me this could work out, but as I said, don't know if I've already tried it 🤷
