### ISSUE TITLE
Is ktfmt used on itself?

### ISSUE THREAD

**Issue by grodin** [facebook/ktfmt#464]
Starting work on #391, I realised there's no `editorconfig` and checking the CI setup, there's no formatting check step there either.

My main concern is to avoid misformatting the work I'm about to do, but I thought it was a potential source of contributor friction so worth raising as an issue.

Happy to help on this too if wanted.

**Comment by hick209** [comment]
We do indeed run ktfmt on ktfmt code (🤯).
Feel free to improve the process (adding `editorconfig` file), but we also do run the formatting to the code when we import your PR internally so don't worry about misformatting things.

**Comment by nreid260** [comment]
In the past, I've been told not to format before sending a PR. The reasoning is that, the PR is probably changing the formatter behaviour, which creates a disproportionate amount of noise. Reformatting is left as a followup.

**Comment by grodin** [comment]
> In the past, I've been told not to format before sending a PR. The reasoning is that, the PR is probably changing the formatter behaviour, which creates a disproportionate amount of noise. Reformatting is left as a followup.

That's a very good point. It's probably better not to include an `editorconfig` then. It doesn't matter too much if FB are formatting the code when they merge internally anyway.

Probably worth mentioning all of the above in `CONTRIBUTING.md`.

**Comment by hick209** [comment]
Good point @grodin! We should change that

**Comment by hick209** [comment]
@grodin do you want to submit a PR for that?
