### ISSUE TITLE
How can I config Intellij plugin?

### ISSUE THREAD

**Issue by Vensent** [facebook/ktfmt#466]
I have configured the spotless gradle plugin and use it as the CI tool. This is what I have configured:

````
kotlin {
        target 'src/*/**/*.kt'
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
        ktfmt('0.46').dropboxStyle().configure {
            it.setMaxWidth(120)
            it.setRemoveUnusedImport(true)
        }
    }
````

I want to make Intellij plugin work for me when I press Ctrl+Alt+L like spotlessApply task do. But Intellij plugin cannot set max width, so it performs not the same as spotlessApply task when I dynamicly reformat code.

Is there any way to configure the Intellij plugin?
Thanks.

**Comment by greyhairredbear** [comment]
At this time, no. This is definitely a request for a new feature. Pretty sure it'd be possible to implement, but I'm not sure it is a target of ktfmt to be configurable. Would be nice if a maintainer could answer this (@hick209 mabye?). 

Btw: 

```
trimTrailingWhitespace()
indentWithSpaces()
endWithNewline()
```

should probably all work out of the box, if I'm not mistaken. 

Not sure if ktfmt removes unused imports by default, but I can recommend `Tools>Actions on Save` in IntelliJ: Here you can check `Reformat code` and `Optimize imports`, which should give you the behavior on saving (although probably not when pressing the format shortcut).

**Comment by Vensent** [comment]
Finally, I have to download the source code of  Intellij plugin and modified some code to satisfy my requirement.
