### ISSUE TITLE
Consider providing a binary jar

### ISSUE THREAD

**Issue by Goooler** [facebook/ktfmt#485]
```sh
chmod +x ktfmt-0.50-jar-with-dependencies.jar
./ktfmt-0.50-jar-with-dependencies.jar
zsh: exec format error: ./ktfmt-0.50-jar-with-dependencies.jar
```

We can't execute this jar directly now, I did something to ktlint like:

https://github.com/pinterest/ktlint/blob/c7083ada451ff0d72a3edb2b3a9d485ee3f0cf96/ktlint-cli/build.gradle.kts#L84-L104

or

https://github.com/Goooler/StringResExporter/blob/5ccfe8ae50aedb10523d3f05ae701a6653ea8763/build.gradle.kts#L74-L94

so that jars can be executed directly.

I'm unfamiliar with Maven, but I would be willing to send a PR if I can do...

**Comment by Goooler** [comment]
Yeah, you can run it like a normal jar with `java -jar`. Actually, it still depends on your local JDK, but you can execute it like binary applications like the others on Unix.

**Comment by hick209** [comment]
Sounds good to me then! @Goooler feel free to submit a PR since from our end this is unlikely to get prioritized any time soon.

**Comment by Goooler** [comment]
It would be easier to do this if we could migrate the core project build to Gradle, is there any plan to migrate?

**Comment by hick209** [comment]
No plans on our side, but I don't see a reason not to do that other than the work required for it and extensive testing to make sure nothing breaks.

I would actually be nice to do since other parts of this project are on Gradle already.
This is just not something that is currently on the roadmap.

**Comment by Goooler** [comment]
May I file a new issue and try to send a PR?

**Comment by hick209** [comment]
If you are feeling like it, feel free to send a PR, I'll gladly take that in 😃

**Comment by hick209** [comment]
Closing the issue as this is not something we'll actively work on and it's also not on our roadmap.
Again we'd be happy to take a PR for it

**Comment by Goooler** [comment]
Just for a note, this feature should be succeeded by #441.
