### ISSUE TITLE
ver 1.1.0.51 update breaks ktfmt intellij plugin setting screen if style is "Dropbox"

### ISSUE THREAD

**Issue by funkyidol** [facebook/ktfmt#486]
The latest update 1.1.0.51 has a breaking change which removes " Dropbox" style. This breaks the plugin settings screen as it doesnt load if the formatting style is currently set to dropbox.

https://github.com/facebook/ktfmt/commit/4a393bb8c1156a4a0fd1ab736c02ca8dbd39a969

Workaround:
 - delete the ktfmt.xml from your .idea plugin. This resets the setting for ktfmt. Now go to intellij settings and re-enable ktfmt and change formating to kotlinlang

**Comment by hick209** [comment]
Thanks for reporting it @funkyidol!

Do you think this is something we could fix on ktfmt's end or did you just wanted to make sure we are aware of this and share a workaround?

**Comment by funkyidol** [comment]
I wanted to do both, share the workaround and bring it to the notice of the ktfmt team so that the issue can be addressed in the intellij plugin via an update.

**Comment by hick209** [comment]
Does this still happen after https://github.com/facebook/ktfmt/pull/503 ?

@rock3r introduced the concept of migration there, which hopefully would help deal with this case here as well

**Comment by hick209** [comment]
Closing as I suspect this was fixed by #503, if not the case, please feel free to reopen
