### ISSUE TITLE
IDEA plugin v1.1.0.51 with Kotlinlang formats incorrectly

### ISSUE THREAD

**Issue by akheron** [facebook/ktfmt#489]
After upgrading the ktfmt IDEA plugin to 1.1.0.51, configured to use the Kotlinlang style, the Reformat code action behaves differently than when running ktfmt v0.51 directly. Specifically, it moves the closing parenthesis of multiline function calls to the previous line:

Expected:
```
foo(
    1,
    2
)
```
Actual:
```
foo(
    1,
    2)
```

Is this expected, or is there a bug in the IDEA plugin?

**Comment by asapha** [comment]
Both the plugin and the cli have the new (undesired) behavior on my end.
Are you sure you're running 0.51?

```
brew info ktfmt

==> ktfmt: stable 0.51 (bottled)
Kotlin code formatter
https://facebook.github.io/ktfmt/
Installed
```

Also, see #482.

**Comment by YarnSphere** [comment]
I can't fully reproduce what you describe, @akheron. I get your "Actual" output both when running ktfmt v0.51 directly (well, in my case via the Spotless Gradle plugin) and via the IDEA plugin, so at least both outputs are consistent.

However, I would like to reiterate your question to the ktfmt developers, is this new output expected? I see no mentions of the change in the changelog, and it seems to go against Kotlinlang conventions.

**Comment by akheron** [comment]
I'm running ktfmt via the Gradle plugin `com.ncorti.ktfmt.gradle`, and it indeed seems to still use an older version of ktfmt. Sorry for the confusion! I opened a new issue #490 about the formatting change.
