### ISSUE TITLE
Usage tabs on playground page don't work

### ISSUE THREAD

**Issue by rock3r** [facebook/ktfmt#505]
https://github.com/user-attachments/assets/60ff5cf2-c783-4d40-837f-92be89595175

Chrome stable, macOS

**Comment by hick209** [comment]
Weird, it works fine for me here, same setup macOS 14.5 ARM and Chrome stable 127.0.6533.99

Let's see what happens after the release of the new version

**Comment by rock3r** [comment]
I tried with and without ad blocker just in case, same result. Maybe it's just my browser

**Comment by hick209** [comment]
@rock3r, could you try in another browser (safari) and see if that works for you? I'm inclined to close as we cannot repro it

**Comment by rock3r** [comment]
Must be something weird with my browser, I'll close.
