### ISSUE TITLE
Android Studio plugin adds trailing commas

### ISSUE THREAD

**Issue by alvindizon** [facebook/ktfmt#519]
Just tried https://plugins.jetbrains.com/plugin/14912-ktfmt and found that it adds trailing commas, is this the intended behavior? Running  the Gradle task `spotlessCheck` doesn't add commas.

**Comment by hick209** [comment]
Yes, this is intentional for styles that use that

See here
https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt#L47-L54

And here
https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/format/Formatter.kt#L45-L66
