### ISSUE TITLE
Possibility of replacing intellij psi with an alternate parser

### ISSUE THREAD

**Issue by yissachar** [facebook/ktfmt#525]
The use of the Intellij PSI lib causes ktfmt to be unable to compile to a GraalVM native image due to a kotlinc bug(see https://github.com/oracle/graal/issues/8502 and https://github.com/facebook/ktfmt/issues/441). While ideally kotlinc is fixed upstream so that any lib using it can compile to a native image, it doesn't seem like a fix is imminently arriving. An alternative solution is to replace the use of psi with a different parser with equivalent functionality. My team has written https://github.com/cashapp/kotlin-editor and we use this for general Kotlin AST manipulation and it seems like it would be able to do the job here as well.

Before I spend a bunch of time trying to convert from psi to kotlin-editor though, I'd like to understand if this is work that would be accepted or not. I'm not sure the quality of the ktfmt tests, but hopefully there's good enough coverage that an internal lib replacement like this should be safe.

**Comment by cgrushko** [comment]
Thanks for the suggestion, and - kotlin-editor is really cool!!

The biggest advantage of IntelliJ PSI for us is that it tracks Kotlin very closely (if it doesn't itself underline the Kotlin compiler). In other words, we will ~never be in a situation where Kotlin has a new language feature that's not covered by IntelliJ PSI.

[At a previous job, I wrote a Java parser tailored to my specific use-case, and it was superior to the Java compiler parser (for my use case); but then Java 8 came out, and my priorities shifted, and I didn't have the time to implement the diff between Java 7 and 8. I eventually had to shut down my use-case.]
