### ISSUE TITLE
Continuation indents in KDoc

### ISSUE THREAD

**Issue by bethcutler** [facebook/ktfmt#66]
Continuation indents in KDoc block tags are currently removed.  Is this a specific design decision?

```kotlin
/**
 * Summary fragment.
 * 
 * @param blockTag This is the first
 * block tag.
 */
```

If the block tag wraps onto a new line, ktfmt will not use any indentation, and remove 1- or 2-space indentation that already exists.  Indents of 3 or more spaces will be automatically maintained with ``` marks.

The [Google Style Guide](https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-block-tags) for Java recommends at least 4 spaces indent (consistent with the continuation indent).  I would propose that ktfmt likewise use the continuation indent here.

**Comment by cgrushko** [comment]
It's probably a bug. Thanks for reporting! we'll take a look.

**Comment by koljakube** [comment]
I believe this issue could be closed. Ktfmt currently inserts correct continuation indents in KDoc `@property` and `@param` tags, at least in my current testing using the IntelliJ plugin.

**Comment by hick209** [comment]
Thanks for catching that, @koljakube. Closing the issue
